#
#    ███████╗██████╗░░█████╗░░██████╗░██████╗
#    ╚════██║██╔══██╗██╔══██╗██╔════╝██╔════╝
#    ░░███╔═╝██████╦╝██║░░██║╚█████╗░╚█████╗░
#    ██╔══╝░░██╔══██╗██║░░██║░╚═══██╗░╚═══██╗
#    ███████╗██████╦╝╚█████╔╝██████╔╝██████╔╝
#    ╚══════╝╚═════╝░░╚════╝░╚═════╝░╚═════╝░
# разработчик точно не хуесос
# https://bio.hushworld.fun/

settings:
  interval: 1 # в минутах
  bossbar:
    name: '&c%name% &fпоявился на &7/warp &epvp'
    color: RED
    style: SOLID
locations:
  spawnLocation:

commands:
  player1: p give %player% 200
  player2: p give %player% 150
  player3: p give %player% 100

types:
  boss1:
    spawn:
      type: WITHER
      health: 10.0
      name: '&dГнилостный Властелин'
  boss2:
    spawn:
      type: EVOKER
      health: 10.0
      name: '&dПовелитель Заклинаний'
  boss5:
    spawn:
      type: WITHER_SKELETON
      health: 10.0
      name: '&dСкелет Уничтожения'
  boss6:
    spawn:
      type: CREEPER
      health: 10.0
      name: '&dВзрывной Повелитель'
  boss7:
    spawn:
      type: ZOMBIE
      health: 10.0
      name: '&dНежить-Живодер'
message:
  spawn:
    - ''
    - '   &fБосс: %name%'
    - ''
    - '   &fПоявился на &7/warp &epvp'
    - ''
    - '   &fТоп три игрока по нанесенным урона боссу'
    - '   &fПолучат игровые &eрубли!'
    - ''
  death:
    - '&6╔═══════════════════════════════╗'
    - '&6║'
    - '&6║   &fБосс: %name%'
    - '&6║'
    - '&6║   &fБыл &c&lПОВЕРЖЕН'
    - '&6║'
    - '&6║  &fТоп &cтри &fигрока по нанесенному &eурону'
    - '&6║'
    - '&6║   &fI. &E%player1%'
    - '&6║   &fII.  &e%player2%'
    - '&6║   &fIII. &e%player3%'
    - '&6║'
    - '&6║   &fВсе &cони &fполучали &eигровые &fрубли!'
    - '&6║'
    - '&6╚═══════════════════════════════╝'
